### ISSUE TITLE
manylinux_2_28 trying to use rust-cross/manylinux_2_24

### ISSUE THREAD

**Issue by martinhoyer** [PyO3/maturin-action#137]
Cross compilation broken when specifying manylinux: 2_28.
```
    steps:
    - uses: actions/checkout@v3
    - uses: messense/maturin-action@v1.35.0
      with:
        manylinux: 2_28
        target: ppc64le
```

```
Run messense/maturin-action@v1.35.0
  with:
    manylinux: 2_28
    target: ppc64le
    command: build
    args: --release --sdist -o dist --find-interpreter
    token: ***
Found maturin version requirement maturin>=0.14,<0.15 specified in pyproject.toml
Found maturin release from manifest: v0.14.10
Pull Docker image
  Using ghcr.io/rust-cross/manylinux_2_24-cross:ppc64le Docker image
  /usr/bin/docker pull ghcr.io/rust-cross/manylinux_2_24-cross:ppc64le
  Error response from daemon: Head "https://ghcr.io/v2/rust-cross/manylinux_2_24-cross/manifests/ppc64le": denied
```

Workaround is to specify the correct version, e.g. 
```
      with:
        manylinux: 2_28
        target: s390x
        container: ghcr.io/rust-cross/manylinux_2_28-cross:s390x
```
