### ISSUE TITLE
Action for generate CI matrix

### ISSUE THREAD

**Issue by samuelcolvin** [PyO3/maturin-action#166]
I maintain three packages that use maturin-action, and it's great.

The hardest part is setting up CI to generate all the right binaries.

I propose we create a separate action to generate the github actions matrix with the right variables set for `maturin-action` to use to generate binaries.

The [list-python-dependencies](https://github.com/samuelcolvin/list-python-dependencies) package, and in particular it's readme shows the workflow for this:
* separate job to generate matrix info
* the action outputs a pile of JSON defining the jobs to run and variables required for each job, specifically you need to write to the file defined by the `GITHUB_OUTPUT` env var - code example [here](https://github.com/samuelcolvin/list-python-dependencies/blob/43f660fbd655f25c3e3ebd3165b09974bbf98e05/list_python_dependencies.py#L35-L42)
* the first job sets `outputs:` to include that output
* second job defines matrix to read that JSON - in the example case `PYTHON_DEPENDENCY_CASE: ${{ fromJSON(needs.find_dependency_cases.outputs.PYTHON_DEPENDENCY_CASES) }}`
* you then define the `maturin-action` in the steps for that job

We could have switches to exclude/skip some targets, much like cibuildwheel [offers](https://cibuildwheel.readthedocs.io/en/stable/options/#examples_1), and a switch for `abi3` etc.

A big advantages of this would be that without any extra work from maintainers, more and more targets could be added as maturin-action supports them - or remove if there are known issues.

Example current `matrix` sections:
* [rtoml](https://github.com/samuelcolvin/rtoml/blob/d79d03faad6d473f2482319365445a50c0df4e18/.github/workflows/ci.yml#L118-L157)
* [watchfiles](https://github.com/samuelcolvin/watchfiles/blob/da0c1f004069399ca9e5dde62e4eaeb5d4a603ea/.github/workflows/ci.yml#L130-L170) (abi3)
* [pydantic-core](https://github.com/pydantic/pydantic-core/blob/330911aedb15653839cea258756f2cf6b622b245/.github/workflows/ci.yml#L272-L326)

Demo of how this might finally look in a workflow yaml file:

```yaml
jobs:
  generate_build_matrix:
    runs-on: ubuntu-latest

    outputs:
      MATURIN_MATRIX: ${{ steps.generate-matrix.outputs.MATURIN_MATRIX }}

    steps:
      - uses: actions/checkout@v3
      - uses: pyo3/maturin-generate-matrix-action@main
        id: generate-matrix
        with:
          exclude: 'win-pypy-*'

  build:
    needs:
      - generate_build_matrix

    strategy:
      # not sure if this actually works or if you need to use a nested matrix namepace as the package above does
      matrix: ${{ fromJSON(needs.generate_build_matrix.outputs.MATURIN_MATRIX) }}

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.python-architecture }}
          
      - run: ...install stuff...

      - name: build
        uses: PyO3/maturin-action@v1
        with:
          command: ${{ matrix.command }}
          target: ${{ matrix.target }}
          manylinux: ${{ matrix.manylinux }}
          container: ${{ matrix.container }}
          args: ${{ matrix.args }}
          # on one combined line:
          matrix_action_config: ${{ matrix.matrix-action-config }}

      - run: twine check --strict ${{ matrix.out-dir }}/*

      - uses: actions/upload-artifact@v3
        with:
          name: pypi_files
          path: ${{ matrix.out-dir }}
```
