### ISSUE TITLE
Target directory is not resolved correctly in a workspace

### ISSUE THREAD

**Issue by Kobzol** [PyO3/maturin-action#190]
Hi! :) I noticed an issue in my Github Actions workflow that uses `maturin-action`. I have a Cargo workspace with a structure like this:
```
/workspace
/workspace/crates/python-crate
```
In my workflow, I first build a wheel using `maturin`:
```yaml
- uses: messense/maturin-action@v1
  with:
    maturin-version: 0.13.5
    manylinux: 2014
    command: build
    args: --manifest-path crates/python-crate/Cargo.toml
```
and then I run a normal `cargo build`, which fails with the following error:
```
error: failed to create directory `/home/runner/work/workspace/target/debug`

Caused by:
  Permission denied (os error 13)
```

The problem is caused by the maturin Docker build leaving files in the `target` directory owned by `root`.
`maturin-action` knows about this, and tries to fix the permissions, however it fails:
```
Fixing file permissions for target directory: crates/python-crate/target
  /usr/bin/sudo chown 1001:123 -R crates/python-crate/target
  chown: cannot access 'crates/python-crate/target': No such file or directory
```

The problem is that it thinks that the `target` directory is where the manifest is located, but since `python-crate` is in a workspace, the `target` directory is actually elsewhere (at `workspace` in my case).

The code which tries to detect the directory is [here](https://github.com/PyO3/maturin-action/blob/7b742b712a09e3aa64c6e6fcc6c864f721ef1e4e/src/index.ts#LL223C38-L223C38).

I was able to resolve this with the following workaround:
```
- uses: messense/maturin-action@v1
  env:
    CARGO_TARGET_DIR: target
```
but it would be nice if this action could auto-detect the correct target directory.
