### ISSUE TITLE
Builds do not appear to overwrite

### ISSUE THREAD

**Issue by chrisjsewell** [PyO3/maturin-action#191]
I have a CI job as below (mainly auto-generated by maturin v1.0.1: `maturin generate-ci github --pytest`).

When I created a Pull-Request, with code changes but not updating the package version,
I was surprised that the tests failed.
It appears this was because it was using a cached build of that package version,
and indeed when I updated the version the job began to pass.

Is this expected?
For PRs CI, obviously, I would expect that I would not have to always update the version to have it pass.

```yaml
name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter
          sccache: 'true'
          manylinux: auto
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist
      - name: pytest
        shell: bash
        run: |
          set -e
          pip install markdown_it_pyrs --find-links dist --force-reinstall
          pip install pytest pytest-param-files
          pytest
```
