### ISSUE TITLE
Openssl

### ISSUE THREAD

**Issue by aersam** [PyO3/maturin-action#192]
Hi there

I am trying to build some rust / python package with PO3 and i'm overwhelmed by how great this works! However one thing I came across is that it's not easy to use this action to build a package that references native-tls/openssl. The simpliest option is to use vendor-ed openssl, but I think that's not really a good thing to do. 

I tried just using adapting the cryptography containers which seem to be quite what I need, but those miss pip. So I tried setting `before-script-linux: python -m ensurepip --upgrade` but this is executed too late. 

I cannot believe that I'm the first one trying this, is there any guidance/docs for using native-tls? Or you just just add `python -m ensurepip` 

Here's the CI.yml I tried for linux:

```yml
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: 
          - { NAME: "x86_64", CONTAINER: "ghcr.io/pyca/cryptography-manylinux2014:x86_64" }
          - { NAME: "aarch64", CONTAINER: "ghcr.io/pyca/cryptography-manylinux2014_aarch64" }
          - { NAME: "x86_64", CONTAINER: "ghcr.io/pyca/cryptography-musllinux_1_1:x86_64" }
          - { NAME: "aarch64", CONTAINER: "ghcr.io/pyca/cryptography-manylinux2014_aarch64" }
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        env:
          OPENSSL_DIR: /usr/local/ssl
        with:
          target: ${{ matrix.target.NAME }}
          container: ${{ matrix.target.CONTAINER }}
          args: --release --out dist --find-interpreter
          sccache: 'true'
          before-script-linux: python -m ensurepip --upgrade
          manylinux: auto
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist
```
