### ISSUE TITLE
Linux i686 build can't find rustup

### ISSUE THREAD

**Issue by LilyFoote** [PyO3/maturin-action#196]
Today my release builds started failing with this error:

```
Run PyO3/maturin-action@v1
  with:
    target: i686
    args: -i 3.9 --release --out dist
    working-directory: python
    manylinux: auto
    token: ***
    command: build
    sccache: false
Pull Docker image
  Using quay.io/pypa/manylinux2014_i686:latest Docker image
  /usr/bin/docker pull quay.io/pypa/manylinux2014_i686:latest
  latest: Pulling from pypa/manylinux2014_i686
  ce510b3e7858: Pulling fs layer
  448bf5d72ce7: Pulling fs layer
  e734b0727b14: Pulling fs layer
  a90af3c9142b: Pulling fs layer
  6f3005afbbb5: Pulling fs layer
  b4c368eef89c: Pulling fs layer
  3ed06a6c4e7a: Pulling fs layer
  b9f8f0fa7bf3: Pulling fs layer
  c87c5e449c15: Pulling fs layer
  a5cfdc53bed6: Pulling fs layer
  3eba075aa689: Pulling fs layer
  3ab6bb6c934b: Pulling fs layer
  925fd9077621: Pulling fs layer
  bf13fcd24641: Pulling fs layer
  987d453d87ed: Pulling fs layer
  86af6abf76c7: Pulling fs layer
  a52c7bd6a27d: Pulling fs layer
  637d11aa4ba0: Pulling fs layer
  da605448f52f: Pulling fs layer
  a934b7fc59a5: Pulling fs layer
  371cd3759536: Pulling fs layer
  e8647ce34692: Pulling fs layer
  a90af3c9142b: Waiting
  6f3005afbbb5: Waiting
  b4c368eef89c: Waiting
  3ed06a6c4e7a: Waiting
  b9f8f0fa7bf3: Waiting
  c87c5e449c15: Waiting
  a52c7bd6a27d: Waiting
  637d11aa4ba0: Waiting
  da605448f52f: Waiting
  a934b7fc59a5: Waiting
  371cd3759536: Waiting
  e8647ce34692: Waiting
  3eba075aa689: Waiting
  3ab6bb6c934b: Waiting
  371cd3759536: Download complete
  e8647ce34692: Verifying Checksum
  e8647ce34692: Download complete
  da605448f52f: Verifying Checksum
  da605448f52f: Download complete
  3ed06a6c4e7a: Pull complete
  b9f8f0fa7bf3: Pull complete
  c87c5e449c15: Pull complete
  a5cfdc53bed6: Pull complete
  3eba075aa689: Pull complete
  3ab6bb6c934b: Pull complete
  925fd9077621: Pull complete
  bf13fcd24641: Pull complete
  987d453d87ed: Pull complete
  86af6abf76c7: Pull complete
  a52c7bd6a27d: Pull complete
  637d11aa4ba0: Pull complete
  da605448f52f: Pull complete
  a934b7fc59a5: Pull complete
  371cd3759536: Pull complete
  e8647ce34692: Pull complete
  Digest: sha256:e2df73fcd9e8ad41076d5eb55d815f17c68a7f4998d9b2966b0050a3fc27c332
  Status: Downloaded newer image for quay.io/pypa/manylinux2014_i686:latest
  quay.io/pypa/manylinux2014_i686:latest
Cleanup build scripts artifact directory
/usr/bin/docker run --rm --workdir /home/runner/actions-runner/_work/kolo/kolo/python -e DEBIAN_FRONTEND=noninteractive -e ARCHFLAGS -e _PYTHON_SYSCONFIGDATA_NAME -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e CARGO_INCREMENTAL -e CARGO_TERM_COLOR -v /tmp/run-maturin-action.sh:/tmp/run-maturin-action.sh -v /home/runner/actions-runner/_work/kolo/kolo:/home/runner/actions-runner/_work/kolo/kolo quay.io/pypa/manylinux2014_i686:latest /tmp/run-maturin-action.sh
WARNING: The requested image's platform (linux/386) does not match the detected host platform (linux/amd64) and no specific platform was requested
Install Rust
  which: no rustup in (/opt/rh/devtoolset-10/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
  /usr/local/bin/manylinux-entrypoint: line 9:     7 Segmentation fault      (core dumped) linux32 "$@"
  Error: The process '/usr/bin/docker' failed with exit code 139
      at ExecState._setResult (/home/runner/actions-runner/_work/_actions/PyO3/maturin-action/v1/dist/index.js:1702:25)
      at ExecState.CheckComplete (/home/runner/actions-runner/_work/_actions/PyO3/maturin-action/v1/dist/index.js:1685:18)
      at ChildProcess.<anonymous> (/home/runner/actions-runner/_work/_actions/PyO3/maturin-action/v1/dist/index.js:1579:27)
      at ChildProcess.emit (node:events:527:28)
      at maybeClose (node:internal/child_process:1092:16)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
  Error: The process '/usr/bin/docker' failed with exit code 139
```

I successfully released with the exact same build configuration yesterday. Retrying the build fails with the same error.

The relevant part of my release workflow file:

```yaml
  linux:
    name: Build wheels on Linux
    runs-on: buildjet-2vcpu-ubuntu-2204
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        target: [x86_64, i686]
        include:
          - python-version: "pypy-3.9"
            target: x86_64
          - python-version: "pypy-3.10"
            target: x86_64

    steps:
      - uses: actions/checkout@v3
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: -i ${{ matrix.python-version }} --release --out dist
          working-directory: python
          manylinux: auto

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - run: pip install kolo --find-links=./python/dist/
      - run: pip install pytest
      - name: Test wheel
        run: KOLO_PATH=$(realpath ./python) pytest ./python/tests/test_cli.py

      - uses: actions/upload-artifact@v3
        with:
          path: python/dist/*.whl
```
