### ISSUE TITLE
rust-toolchain argument seems to not have any effect 

### ISSUE THREAD

**Issue by planck-length** [PyO3/maturin-action#201]
Not sure am I setting this correctly. Here's my yml
```
jobs:
  build-wheel:
    name: Build Wheel
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: cp310
        with:
          python-version: '3.10'
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          rust-toolchain: nightly
          command: build
          args: --release --out wheels -i python3.10 -b pyo3
          manylinux: auto
        env:
          CARGO_REGISTRIES_ARTIFACTORY_TOKEN: ${{ secrets.TOKEN}}
```
In the log I see
```
  info: override toolchain for '/runner/_work/repo...' set to 'stable-x86_64-unknown-linux-gnu'
 
    stable-x86_64-unknown-linux-gnu unchanged - rustc 1.71.1 (eb26296b5 2023-08-03)
```
