### ISSUE TITLE
Args passing to runner incorrectly

### ISSUE THREAD

**Issue by npapapietro** [PyO3/maturin-action#227]
I'm attempting to run a testpypi in my CI with the following workflow job step:

```yaml
    - name: Publish to PyPI
      uses: PyO3/maturin-action@v1
      env:
        MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN_TEST }}
      with:
        command: upload
        args: "-r testpypi --skip-existing dist/*"
```

And the job runs via
```
/home/runner/work/_temp/01b59811-e59d-4b85-a41e-ca41aefcbc6d/maturin upload --repository --skip-existing ...
```

 Where the arg for `-r`/`--repository` is removed. I've used the environment var `MATURIN_REPOSITORY` to work around for now.

Here is the job that attempted to run https://github.com/npapapietro/liesym/actions/runs/6828779586/job/18573598558 if you'd like to further inspect
