### ISSUE TITLE
Allow specifying maturin version by git commit/branch

### ISSUE THREAD

**Issue by stinodego** [PyO3/maturin-action#228]
The maturin action only supports tagged releases, as documented in the README.

Recently, I ran into a bug and wanted to use the latest commit on the main branch to build my project. However, this is not currently possible. I have the git branch specified in my `pyproject.toml`:

```toml
[build-system]
requires = ["maturin @ git+https://github.com/PyO3/maturin.git@main"]
build-backend = "maturin"
```

Maturin action recognized this, but doesn't allow it and installs the latest released version (which does not include the fix I require).
```
Found maturin version requirement maturin @ git+https://github.com/PyO3/maturin.git@main specified in pyproject.toml
Warning: No maturin release found from requirement maturin @ git+https://github.com/PyO3/maturin.git@main, fallback to latest
```

I It woul be great if we could at least use the latest version on the main branch. Though I understand this may be hard to support.
