### ISSUE TITLE
feature request: support PyPI OIDC

### ISSUE THREAD

**Issue by sxlijin** [PyO3/maturin-action#255]
It would be nice if I could use their OIDC with maturin-action; to get around this, I ended up doing some shenanigans to get our (new) release process working with OIDC, which publishes artifacts built using maturin:

```
  build:
      ... some matrix stuff ...

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix._.name }}
          path: dist

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4

      - run: mkdir dist && mv wheels-*/* dist

      # authz is managed via OIDC configured at https://pypi.org/manage/project/$PROJECT/settings/publishing/
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
```
