### ISSUE TITLE
mismatch python version of maturin in linux

### ISSUE THREAD

**Issue by franklucky001** [PyO3/maturin-action#299]
# linux workflow
```yaml
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10', '3.11', '3.12' ]
        target: [x86_64]
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}-unknown-linux-gnu

      - uses: actions/setup-python@v4
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pip
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          before-script-linux: which maturin && whereis python && pip3 -V
          target: ${{ matrix.target }}
          manylinux: auto
          args: --release --out dist --manifest-path bytepiece-py/Cargo.toml

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist/*.whl
```
# jobs-x86_64-linux python 3.8 - 3.12, all of maturin is python3.7 version , #before-script-linux#: `which maturin && whereis python && pip3 -V` got info,
```text
/usr/local/bin/maturin
  python: /usr/bin/python /usr/bin/python2.7 /usr/lib/python2.7 /usr/lib64/python2.7 /etc/python /usr/local/bin/python3.8 /usr/local/bin/python3.12 /usr/local/bin/python3.11 /usr/local/bin/python3.7 /usr/local/bin/python3.9 /usr/local/bin/python3.6 /usr/local/bin/python3.13t /usr/local/bin/python3.13 /usr/local/bin/python3.10 /usr/include/python2.7 /opt/_internal/cpython-3.7.17/bin/python /opt/_internal/cpython-3.7.17/bin/python3.7m /opt/_internal/cpython-3.7.17/bin/python3.7m-config /opt/_internal/cpython-3.7.17/bin/python3.7-config /opt/_internal/cpython-3.7.17/bin/python3.7 /opt/_internal/cpython-3.8.20/bin/python3.8-config /opt/_internal/cpython-3.8.20/bin/python /opt/_internal/cpython-3.8.20/bin/python3.8 /opt/_internal/cpython-3.9.20/bin/python /opt/_internal/cpython-3.9.20/bin/python3.9-config /opt/_internal/cpython-3.9.20/bin/python3.9 /opt/_internal/cpython-3.10.15/bin/python3.10-config /opt/_internal/cpython-3.10.15/bin/python /opt/_internal/cpython-3.10.15/bin/python3.10 /opt/_internal/cpython-3.11.1
  pip 24.0 from /opt/_internal/cpython-3.7.17/lib/python3.7/site-packages/pip (python 3.7)
```
## when maturin build
Found pyo3 bindings
🐍 Found CPython 3.7m at /opt/python/cp37-cp37m/bin/python3

## my repos [bytepiece](https://github.com/franklucky001/bytepiece-rs/actions/runs/11871186105)
