### ISSUE TITLE
Binaries produced for MacOs fail to run

### ISSUE THREAD

**Issue by concur1** [PyO3/maturin-action#334]
When running binaries inside whl's produced for MacOs I get the following error:
```
dyld[84491]: Library not loaded: /opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/Python
  Referenced from: <065BEC1E-C130-3AED-AD4A-9B5DCC3DC3AF> /Users/o/projects/other/sqrufftest/.venv/bin/sqruff
  Reason: tried: '/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/Python' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/Python' (no such file), '/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/Python' (no such file)
fish: Job 1, 'sqruff' terminated by signal SIGABRT (Abort)
```

The binaries were produced with the following gitghub action yaml file:
```yaml
# This file is autogenerated by maturin v1.7.8
# To update, run
#
#    maturin generate-ci github --manifest-path crates/cli/Cargo.toml --output .github/workflows/python-ci.yaml
#
name: CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  macos:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false # Allow other variants to continue even if one fails
      matrix:
        platform:
          - runner: macos-13
            target: x86_64
          - runner: macos-14
            target: aarch64
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # ratchet:actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Build wheels
        uses: PyO3/maturin-action@36db84001d74475ad1b8e6613557ae4ee2dc3598 # ratchet:PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          args: --release  --interpreter python3.10 python3.11 python3.12 python3.13 --out dist --manifest-path crates/cli/Cargo.toml
          sccache: "true"
      - name: Upload wheels
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # ratchet:actions/upload-artifact@v4
        with:
          name: wheels-macos-${{ matrix.platform.target }}
          path: dist
```

You can find an example of one of these whls here: https://github.com/quarylabs/sqruff/actions/runs/13863317954/artifacts/2754977129 produced from this GHA workflow run: https://github.com/quarylabs/sqruff/actions/runs/13863317954
