### ISSUE TITLE
New Zig Version Causing Compilation Errors

### ISSUE THREAD

**Issue by kahojyun** [PyO3/maturin-action#335]
## Issue

Compilation error occurs under Linux when using the `--zig` option.

```yaml
- name: Build wheels
  uses: PyO3/maturin-action@v1
  with:
    target: ${{ matrix.target }}
    args: --release --out dist --zig
    sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
    manylinux: auto
```

```
error: /home/runner/work/fricon/fricon/target/release/deps/libsqlx_macros-406fbcf041baea62.so: undefined symbol: __ubsan_handle_type_mismatch_v1
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-0.8.3/src/lib.rs:64:1
   |
64 | pub extern crate sqlx_macros;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Comparison with previous successful action runs shows that the installed `ziglang` package version changed from `0.13.0.post1` to `0.14.0`

## Suggestion

Specify a version cap when installing `ziglang`

Current workaround: Install `ziglang<0.14` before running `maturin-action`

```
python -m pip install "ziglang<0.14"
```

## Additional Information

The following debugging information may help identify the error's cause:

- `aarch64` version compiles normally
- Cross-compilation from macOS to Linux works normally
- Zig provides UBSan runtime in `0.14.0` https://ziglang.org/download/0.14.0/release-notes.html#UBSan-Runtime
