### ISSUE TITLE
sccache doesn't work with 2_28 because pip isn't available

### ISSUE THREAD

**Issue by benbrandt** [PyO3/maturin-action#336]
It seems the pip module isn't available in all of the Docker containers.

Config:
```
name: Build wheels
        uses: PyO3/maturin-action@5f8a1b3b0aad13193f46c9131f9b9e663def8ce5
        with:
          target: ${{ matrix.target }}
          args: --release --out dist
          manylinux: 2_28
          working-directory: bindings/python
          sccache: true
```
Output
```
Install sccache
  /usr/bin/python3: No module named pip
```
