### ISSUE TITLE
linux ubuntu-latest, x86_64-unknown-linux-musl, musllinux_1_1  - Compiler not supported

### ISSUE THREAD

**Issue by gaborbernat** [PyO3/maturin-action#348]
https://github.com/tox-dev/toml-fmt/actions/runs/14742133285/job/41382387489?pr=51#logs

```
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.8
💥 maturin failed
  Caused by: Failed to run rustc to get the host target
  Caused by: error from command -- stderr:

sccache: error: failed to execute compile
sccache: caused by: Compiler not supported: "error: toolchain \'stable-x86_64-unknown-linux-gnu\' is not installed\nhelp: run `rustup toolchain install stable-x86_64-unknown-linux-gnu` to install it\n"
```

Ideas why this could be?

**Comment by gaborbernat** [comment]
@messense any idea what could be going here?

**Comment by messense** [comment]
Looks like a sccache bug? What if you switch to Rust stable? consider file an issue if it still happens on Rust stable: https://github.com/mozilla/sccache/issues

**Comment by gaborbernat** [comment]
How do I switch to rust stable?

**Comment by orhun** [comment]
I'm hitting the same issue [here](https://github.com/orhun/git-cliff/actions/runs/15390833952/job/43299820365), is there any fix available yet?

**Comment by messense** [comment]
I think there is something wrong when `rust-toolchain.toml` set toolchain to `nightly`, sccache seems to want to try stable rustc somehow.

**Comment by FloezeTv** [comment]
I ran into the same issue when setting `rust-toolchain.toml` to `1.87` (and assume that it happens whenever it is set to something other than `stable`).

From my debugging I am relatively sure this happens because the `sccache`-server is started in the root directory (`/`).
When `maturin` then wants to [get the `rustc` version](https://github.com/PyO3/maturin/blob/ea5adfc5f44350407bc2d7befc0fffb1b5e633a8/src/target/mod.rs#L714), the call is [wrapped using `sccache`](https://github.com/djc/rustc-version-rs/blob/eeca449cca83e24150e46739e797aa82e9142809/src/lib.rs#L202-L205) and executed by the `sccache`-server.
However, as the `sccache`-server is started in the system's root directory, it executes `rustc` there, which in turn does not pick up the `rust-toolchain.toml` (because it does not exist in the system root but only in the project) and will instead try to use the `stable`-channel by default.
However, as this channel [was removed](https://github.com/PyO3/maturin-action/blob/241c7a2b97ee12b8a1761dc078e928debe487be2/src/index.ts#L666), the `rustc` call fails with the `rustup`-output telling you to install the required `stable` toolchain.
`cargo` commands work without a problem, only calling `rustc` directly doesn't work (I guess `cargo` passes the correct toolchain).

As a **workaround**, one can manually start the `sccache`-server in the project directory:
```yaml
- uses: PyO3/maturin-action@v1
  with:
    sccache: "true"
    before-script-linux: |
      # Manually install `sccache`,
      # as the script is called before `sccache` is installed by the action
      uv tool install "sccache>=0.10.0"
      # start the `sccache`-server in the current directory
      # to have calls to `rustc` pick up `rust-toolchain.toml`
      SCCACHE_START_SERVER=1 SCCACHE_NO_DAEMON=1 sccache &
    # other options
```

Alternatively, one can copy `rust-toolchain.toml` to the root-directory:
```yaml
- uses: PyO3/maturin-action@v1
  with:
    sccache: "true"
    before-script-linux: |
      # Copy `rust-toolchain.toml` such that `sccache`
      # calls to `rustc` pick up `rust-toolchain.toml`
      cp rust-toolchain.toml /
    # other options
```

And I guess it would also be possible to install the `stable`-toolchain again.

I think the reason the builds for other platforms don't fail is because the default `stable`-toolchain is only removed in the docker-build.
The `macos` and `windows` builds use the host-build, so calling `rustc` to check the version would report the version information of the installed `stable`-toolchain.
I don't know if `maturin` getting the wrong version information has any consequences on the build.
