### ISSUE TITLE
Option for git credential store using access token to clone private repositories

### ISSUE THREAD

**Issue by VanillaBrooks** [PyO3/maturin-action#57]
I'm trying to run this action to create python bindings for a project that contains a `git` dependency in Cargo.toml. Normally I can use something like [de-vri-es/setup-git-credentials](https://github.com/de-vri-es/setup-git-credentials) to store an access token so that `cargo build` will complete without issues. 

However, due to the use of docker in `maturin-action` I believe that these credentials are not being passed into the container. Therefore, the internal `maturin` commands fail for me with:

```
Caused by:
  failed to load source for dependency `$private_repo`
Caused by:
  failed to authenticate when downloading repository
  * attempted to find username/password via git's `credential.helper` support, but failed
  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
 [ https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-c](https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli)
```

would it be possible to add a `git_token` input (or similar) to this project so that projects with private repos can be built? Alternatively, perhaps copy any `.git-credentials` files into the container so that they are configured externally?

## Example Action

I can also put together a minimal repo with a private git dep to demonstrate the issue if needed

```yaml
name: pybindings

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64, i686]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64
    # add git credentials so we can `cargo build` the repo with git dependencies
    - name: add git credentials for clone
      uses: de-vri-es/setup-git-credentials@v2
      with:
        credentials: ${{secrets.GIT_CREDENTIALS}}
    # build
    - name: Build repo with private deps
      run: cargo build --color=always
    # verify that we can run `maturin build` naturally without maturin-action
    - name: Build python bindings manually
      run: |
        cd pybind
        cargo install maturin
        maturin build
    # then do the manylinux build with maturin-action
    # //this fails//
    - name: build python wheels
      uses: messense/maturin-action@v1
      with:
        target: ${{ matrix.target }}
        manylinux: auto
        args: --release --out dist -m pybind/Cargo.toml

```
